import { db } from './firebase.js';
import { collection, getDocs, doc, updateDoc, query, orderBy, serverTimestamp } from 'https://www.gstatic.com/firebasejs/12.1.0/firebase-firestore.js';
import { waitForAdmin } from './admin-auth.js';

const state={orders:[],selected:null};
const $=s=>document.querySelector(s);
const money=v=>`₦${Number(v||0).toLocaleString('en-NG')}`;
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const label=v=>String(v||'new').replaceAll('_',' ');
const reference=o=>o.trackingCode||`RG-${String(o.id||'').slice(0,6).toUpperCase()}`;

async function loadOrders(){
  await waitForAdmin();
  try{const snap=await getDocs(query(collection(db,'orders'),orderBy('createdAt','desc')));state.orders=snap.docs.map(d=>({id:d.id,...d.data()}))}catch(error){console.warn('Orders could not be loaded:',error);state.orders=[]}
  render();updateMetrics();
}
function render(){const wrap=$('#ordersManager');if(!wrap)return;const filter=$('#orderFilter')?.value||'all';const orders=filter==='all'?state.orders:state.orders.filter(o=>o.status===filter);wrap.innerHTML=orders.length?orders.map(o=>{const items=(o.items||[]).map(i=>`${esc(i.name)} × ${i.quantity}`).join(', ');return `<article class="order-row"><div><span class="order-id">${esc(reference(o))}</span><h3>${esc(o.customer?.name||'Customer')}</h3><p>${esc(o.customer?.phone||'')} · ${esc(o.fulfilment==='delivery'?'Home delivery':'Rushgal pickup')}</p><p class="muted">${items}</p></div><div class="order-side"><strong>${money(o.total)}</strong><span class="order-status">${esc(label(o.status))}</span><button data-order="${o.id}">View order</button></div></article>`}).join(''):`<div class="empty">No orders match this filter.</div>`}
function updateMetrics(){const today=new Date();const sales=state.orders.filter(o=>{const d=o.createdAt?.toDate?.();return d&&d.toDateString()===today.toDateString()&&['confirmed','processing','out_for_delivery','delivered','collected'].includes(o.status)}).reduce((s,o)=>s+Number(o.total||0),0);$('#salesMetric').textContent=money(sales);$('#ordersMetric').textContent=state.orders.filter(o=>o.status==='new').length}
function openOrder(id){const o=state.orders.find(x=>x.id===id);if(!o)return;state.selected=o;const ref=reference(o);$('#orderTitle').textContent=`Order ${ref}`;$('#orderStatus').value=o.status||'new';const address=o.address?`${o.address.address||''}, ${o.address.area||''}`:'Store pickup';const phone=String(o.customer?.phone||'').replace(/\D/g,'');const message=encodeURIComponent(`Hello ${o.customer?.name||''}, this is Rushgal regarding order ${ref}. Your order total is ${money(o.total)}. We are contacting you to confirm your order.`);const whatsapp=phone?`https://wa.me/${phone}?text=${message}`:'';$('#orderDetails').innerHTML=`<div class="order-detail"><p><strong>Order reference</strong><br>${esc(ref)}</p><p><strong>Customer</strong><br>${esc(o.customer?.name||'')}<br>${esc(o.customer?.phone||'')} ${o.customer?.email?`<br>${esc(o.customer.email)}`:''}</p><p><strong>Fulfilment</strong><br>${o.fulfilment==='delivery'?'Home delivery':'Rushgal pickup'}<br>${esc(address)}${o.address?.notes?`<br>Note: ${esc(o.address.notes)}`:''}</p><p><strong>Payment</strong><br>Pay on delivery</p><p><strong>Items</strong><br>${(o.items||[]).map(i=>`${esc(i.name)} × ${i.quantity} — ${money(i.price*i.quantity)}`).join('<br>')}</p><p><strong>Total</strong><br>${money(o.total)}</p>${o.address?.latitude?`<p><strong>GPS</strong><br>${o.address.latitude}, ${o.address.longitude}</p>`:''}${whatsapp?`<p><a class="primary" href="${whatsapp}" target="_blank" rel="noopener">Contact customer on WhatsApp</a></p>`:''}</div>`;$('#orderModal').classList.add('is-open')}
async function saveStatus(){if(!state.selected)return;await waitForAdmin();const status=$('#orderStatus').value;await updateDoc(doc(db,'orders',state.selected.id),{status,updatedAt:serverTimestamp()});state.selected.status=status;$('#orderModal').classList.remove('is-open');await loadOrders()}
document.addEventListener('DOMContentLoaded',()=>{loadOrders();$('#orderFilter')?.addEventListener('change',render);$('#ordersManager')?.addEventListener('click',e=>{const b=e.target.closest('[data-order]');if(b)openOrder(b.dataset.order)});$('#closeOrder')?.addEventListener('click',()=>$('#orderModal').classList.remove('is-open'));$('#saveOrderStatus')?.addEventListener('click',saveStatus)});
