import { db } from './firebase.js';
import { collection, getDocs, addDoc, updateDoc, deleteDoc, doc, serverTimestamp } from 'https://www.gstatic.com/firebasejs/12.1.0/firebase-firestore.js';
const $=s=>document.querySelector(s); const state={zones:[],edit:null};
const money=v=>`₦${Number(v||0).toLocaleString('en-NG')}`; const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
async function load(){const snap=await getDocs(collection(db,'deliveryZones'));state.zones=snap.docs.map(d=>({id:d.id,...d.data()}));render()}
function render(){const el=$('#deliveryZones');if(!el)return;el.innerHTML=state.zones.length?state.zones.map(z=>`<article class="zone-row"><div><strong>${esc(z.name)}</strong><span>${z.active===false?'Disabled':'Active'}</span></div><div><b>${money(z.fee)}</b><button data-edit-zone="${z.id}">Edit</button><button data-delete-zone="${z.id}">Delete</button></div></article>`).join(''):'<div class="empty">No delivery zones configured.</div>'}
function open(z={}){$('#zoneForm').reset();$('#zoneForm').dataset.id=z.id||'';$('#zoneName').value=z.name||'';$('#zoneFee').value=z.fee??'';$('#zoneActive').checked=z.active!==false;$('#zoneModal').classList.add('is-open')}
async function save(e){e.preventDefault();const f=e.currentTarget,id=f.dataset.id;const data={name:$('#zoneName').value.trim(),fee:Number($('#zoneFee').value||0),active:$('#zoneActive').checked,updatedAt:serverTimestamp()};if(id)await updateDoc(doc(db,'deliveryZones',id),data);else await addDoc(collection(db,'deliveryZones'),{...data,createdAt:serverTimestamp()});$('#zoneModal').classList.remove('is-open');await load()}
async function remove(id){if(confirm('Delete this delivery zone?')){await deleteDoc(doc(db,'deliveryZones',id));await load()}}
document.addEventListener('DOMContentLoaded',()=>{load();$('#addZone')?.addEventListener('click',()=>open());$('#closeZone')?.addEventListener('click',()=>$('#zoneModal').classList.remove('is-open'));$('#zoneForm')?.addEventListener('submit',save);$('#deliveryZones')?.addEventListener('click',e=>{const a=e.target.closest('[data-edit-zone]'),d=e.target.closest('[data-delete-zone]');if(a)open(state.zones.find(z=>z.id===a.dataset.editZone));if(d)remove(d.dataset.deleteZone)})});
