import { db } from './firebase.js';
import { collection, getDocs, addDoc, serverTimestamp } from 'https://www.gstatic.com/firebasejs/12.1.0/firebase-firestore.js';

const ASSET='assets/images/';
const fallbackProducts=[
  {id:'look-01',name:'The Occasion Edit',category:'Dresses & occasion',price:null,image:`${ASSET}unnamed%20(1).jpg`},
  {id:'look-02',name:'Everyday Form',category:'Ready to wear',price:null,image:`${ASSET}unnamed%20(10).jpg`},
  {id:'look-03',name:'Statement Pieces',category:'New edit',price:null,image:`${ASSET}unnamed%20(11).jpg`},
  {id:'look-04',name:'The Soft Set',category:'Two-piece sets',price:null,image:`${ASSET}unnamed%20(2).jpg`}
];
const state={products:[],cart:loadCart(),zones:[],deliveryFee:0,fulfilment:'delivery'};
const money=value=>value==null?'Price on request':`₦${Number(value).toLocaleString('en-NG')}`;
const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
function loadCart(){try{return JSON.parse(localStorage.getItem('rushgal-cart')||'[]')}catch{return[]}}
function saveCart(){localStorage.setItem('rushgal-cart',JSON.stringify(state.cart));updateCartCount()}
function updateCartCount(){const count=state.cart.reduce((n,item)=>n+item.qty,0);$$('[data-cart-count]').forEach(el=>el.textContent=count)}
function escapeHtml(value=''){return String(value).replace(/[&<>\'"]/g,char=>{if(char==='&')return '&amp;';if(char==='<')return '&lt;';if(char==='>')return '&gt;';if(char==="'")return '&#39;';return '&quot;'})}

async function loadProducts(){try{const snap=await getDocs(collection(db,'products'));state.products=snap.docs.map(doc=>({id:doc.id,...doc.data()}))}catch(error){console.warn('Product collection unavailable; using local preview catalogue.',error)}if(!state.products.length)state.products=fallbackProducts;renderProducts()}
async function loadDeliveryZones(){try{const snap=await getDocs(collection(db,'deliveryZones'));state.zones=snap.docs.map(doc=>({id:doc.id,...doc.data()})).filter(z=>z.active!==false);renderDeliveryZones()}catch(error){console.warn('Delivery zones unavailable; checkout will require Rushgal confirmation.',error)}}
function renderDeliveryZones(){const select=$('#deliveryZone');if(!select)return;const current=select.value;select.innerHTML='<option value="">Select your delivery area</option>'+state.zones.map(z=>`<option value="${escapeHtml(z.id)}">${escapeHtml(z.name)} — ${money(z.fee)}</option>`).join('');if(current&&state.zones.some(z=>z.id===current))select.value=current;updateDeliveryFee()}
function updateDeliveryFee(){if(state.fulfilment!=='delivery'){state.deliveryFee=0;updateCheckoutSummary();return}const zoneId=$('#deliveryZone')?.value;const zone=state.zones.find(z=>z.id===zoneId);state.deliveryFee=zone?Number(zone.fee||0):0;const status=$('#locationStatus');if(status&&zone)status.textContent=`✓ ${zone.name} selected. Delivery fee: ${money(zone.fee)}.`;updateCheckoutSummary()}
function renderProducts(){const grid=$('#shopGrid');if(!grid)return;const filter=$('#shopFilter')?.value||'all';const products=filter==='all'?state.products:state.products.filter(p=>(p.category||'').toLowerCase().includes(filter));grid.innerHTML=products.length?products.map(productCard).join():`<div class="shop-empty"><strong>No pieces in this edit yet.</strong>Rushgal can add products from the admin dashboard.</div>`}
function productCard(p){const priced=typeof p.price==='number'&&p.price>0;const image=p.image||p.images?.[0]||'';return `<article class="shop-card"><div class="shop-card-image">${p.badge?`<span class="shop-card-badge">${escapeHtml(p.badge)}</span>`:''}<img src="${image}" alt="${escapeHtml(p.name||'Rushgal product')}" loading="lazy"></div><div class="shop-card-body"><div class="shop-card-top"><div><span class="shop-card-category">${escapeHtml(p.category||'Rushgal')}</span><h3>${escapeHtml(p.name||'Untitled piece')}</h3></div><span class="shop-price">${money(p.price)}</span></div><div class="shop-card-actions"><button type="button" data-view="${p.id}">View</button><button type="button" class="add" data-add="${p.id}" ${priced?'':'disabled'}>${priced?'Add to bag':'Price on request'}</button></div></div></article>`}
function addToCart(id){const product=state.products.find(p=>p.id===id);if(!product||typeof product.price!=='number')return;const existing=state.cart.find(i=>i.id===id);if(existing)existing.qty+=1;else state.cart.push({id,name:product.name,price:product.price,image:product.image||product.images?.[0]||'',qty:1});saveCart();renderCart();openCart()}
function changeQty(id,delta){const item=state.cart.find(i=>i.id===id);if(!item)return;item.qty+=delta;if(item.qty<=0)state.cart=state.cart.filter(i=>i.id!==id);saveCart();renderCart()}
function subtotal(){return state.cart.reduce((sum,i)=>sum+i.price*i.qty,0)}
function renderCart(){const wrap=$('#cartItems');if(!wrap)return;wrap.innerHTML=state.cart.length?state.cart.map(i=>`<div class="cart-item"><img src="${i.image}" alt=""><div><h3>${escapeHtml(i.name)}</h3><p>${money(i.price)} each</p><div class="qty"><button data-minus="${i.id}">−</button><span>${i.qty}</span><button data-plus="${i.id}">+</button></div></div><span class="cart-item-total">${money(i.price*i.qty)}</span></div>`).join():`<div class="shop-empty"><strong>Your bag is empty.</strong>Add a piece you love and it will appear here.</div>`;$('#cartSubtotal').textContent=money(subtotal());$('#checkoutButton').disabled=!state.cart.length}
function openCart(){const el=$('#cartDrawer');el.classList.add('is-open');el.setAttribute('aria-hidden','false')}
function closeCart(){const el=$('#cartDrawer');el.classList.remove('is-open');el.setAttribute('aria-hidden','true')}
function openCheckout(){if(!state.cart.length)return;closeCart();$('#checkoutModal').classList.add('is-open');updateCheckoutSummary()}
function closeCheckout(){$('#checkoutModal').classList.remove('is-open')}
function updateCheckoutSummary(){const sub=subtotal();const delivery=state.fulfilment==='delivery'?state.deliveryFee:0;$('#checkoutSubtotal').textContent=money(sub);$('#deliveryFee').textContent=delivery?money(delivery):'FREE';$('#checkoutTotal').textContent=money(sub+delivery);$('#deliveryFields').classList.toggle('is-hidden',state.fulfilment!=='delivery');const place=$('.checkout-form .place');if(place)place.disabled=state.fulfilment==='delivery'&&!$('#deliveryZone')?.value}
function requestLocation(){const status=$('#locationStatus');if(!navigator.geolocation){status.textContent='Location is not supported on this browser.';return}status.textContent='Requesting your location…';navigator.geolocation.getCurrentPosition(pos=>{$('#latitude').value=pos.coords.latitude.toFixed(6);$('#longitude').value=pos.coords.longitude.toFixed(6);status.textContent='✓ Location captured. Rushgal can use it to confirm the delivery area.'},()=>{status.textContent='We could not access your location. You can enter the address manually.'},{enableHighAccuracy:true,timeout:10000})}
function showProductInquiry(id){const p=state.products.find(item=>item.id===id);if(!p)return;const message=`Hi Rushgal, I'd like to ask about ${p.name}. Is it available?`;window.open(`https://wa.me/2347062281152?text=${encodeURIComponent(message)}`,'_blank','noopener')}
async function placeOrder(event){event.preventDefault();const form=event.currentTarget,data=new FormData(form),submit=form.querySelector('.place'),status=$('#checkoutStatus');if(state.fulfilment==='delivery'&&!$('#deliveryZone')?.value){status.textContent='Please select your delivery area.';status.classList.add('show');return}const zone=state.zones.find(z=>z.id===$('#deliveryZone')?.value);const order={customer:{name:data.get('name'),phone:data.get('phone'),email:data.get('email')||''},fulfilment:state.fulfilment,deliveryZone:state.fulfilment==='delivery'?{id:zone?.id||null,name:zone?.name||'',fee:Number(zone?.fee||0)}:null,address:state.fulfilment==='delivery'?{address:data.get('address'),area:zone?.name||'',notes:data.get('notes')||'',latitude:data.get('latitude')||null,longitude:data.get('longitude')||null}:null,items:state.cart.map(i=>({productId:i.id,name:i.name,price:i.price,quantity:i.qty})),subtotal:subtotal(),deliveryFee:state.fulfilment==='delivery'?state.deliveryFee:0,total:subtotal()+(state.fulfilment==='delivery'?state.deliveryFee:0),paymentMethod:'pay_on_delivery',status:'new',createdAt:serverTimestamp()};submit.disabled=true;status.textContent='Submitting your order…';status.classList.add('show');try{const ref=await addDoc(collection(db,'orders'),order);status.textContent=`Order received. Your reference is ${ref.id.slice(0,8).toUpperCase()}. Rushgal will contact you on WhatsApp to confirm.`;state.cart=[];saveCart();renderCart();form.reset();state.deliveryFee=0;updateCheckoutSummary()}catch(error){console.error(error);status.textContent='We could not submit the order yet. Please contact Rushgal on WhatsApp to complete your order.'}finally{submit.disabled=false}}
function bind(){updateCartCount();renderCart();$('#shopFilter')?.addEventListener('change',renderProducts);$('#cartOpen')?.addEventListener('click',openCart);$('#cartOpen2')?.addEventListener('click',openCart);$('#cartClose')?.addEventListener('click',closeCart);$('#cartBackdrop')?.addEventListener('click',closeCart);$('#checkoutButton')?.addEventListener('click',openCheckout);$('#checkoutClose')?.addEventListener('click',closeCheckout);$('#checkoutCancel')?.addEventListener('click',closeCheckout);$$('input[name="fulfilment"]').forEach(input=>input.addEventListener('change',()=>{state.fulfilment=input.value;updateDeliveryFee()}));$('#deliveryZone')?.addEventListener('change',updateDeliveryFee);$('#useLocation')?.addEventListener('click',requestLocation);$('#checkoutForm')?.addEventListener('submit',placeOrder)}
document.addEventListener('DOMContentLoaded',()=>{bind();loadProducts();loadDeliveryZones()});