import { db } from './firebase.js';
import { collection, getDocs, addDoc, serverTimestamp } from 'https://www.gstatic.com/firebasejs/12.1.0/firebase-firestore.js';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const money=v=>{const n=Number(v);return Number.isFinite(n)&&n>0?`₦${n.toLocaleString('en-NG')}`:'Price on request'};
const priceOf=p=>{for(const k of ['price','sellingPrice','salePrice','amount']){const n=Number(p?.[k]);if(Number.isFinite(n)&&n>0)return n}return null};
const stockOf=p=>{const n=Number(p?.stock);return Number.isFinite(n)?n:null};
const soldOut=p=>p?.status==='out_of_stock'||p?.status==='draft'||p?.active===false||p?.available===false||p?.inStock===false||stockOf(p)===0;
const imageOf=p=>p?.images?.[0]||p?.image||'';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const state={products:[],cart:[],zones:[],fee:0,fulfilment:'delivery',selected:null,size:'',colour:''};
function loadCart(){try{const a=JSON.parse(localStorage.getItem('rushgal-cart-v1')||localStorage.getItem('rushgal-cart')||'[]');return Array.isArray(a)?a.map(i=>({...i,qty:Math.max(1,Number(i.qty??i.quantity??1)),price:Number(i.price)||0})):[]}catch{return[]}}
function saveCart(){const s=JSON.stringify(state.cart);localStorage.setItem('rushgal-cart-v1',s);localStorage.setItem('rushgal-cart',s);updateCount()}
function updateCount(){const n=state.cart.reduce((a,i)=>a+(Number(i.qty)||0),0);$$('[data-cart-count]').forEach(x=>x.textContent=n)}
function subtotal(){return state.cart.reduce((a,i)=>a+(Number(i.price)||0)*(Number(i.qty)||0),0)}
function renderCart(){const box=$('#cartItems');if(!box)return;box.innerHTML=state.cart.length?state.cart.map(i=>`<div class="cart-item"><img src="${esc(i.image||'')}" alt=""><div><h3>${esc(i.name)}</h3><p>${money(i.price)} each${i.size?` · Size ${esc(i.size)}`:''}${i.colour?` · ${esc(i.colour)}`:''}</p><div class="qty"><button type="button" data-minus="${esc(i.id)}">−</button><span>${i.qty}</span><button type="button" data-plus="${esc(i.id)}">+</button></div></div><span class="cart-item-total">${money(Number(i.price)*Number(i.qty))}</span></div>`).join(''):'<div class="shop-empty"><strong>Your bag is empty.</strong>Add a piece you love and it will appear here.</div>';$('#cartSubtotal').textContent=money(subtotal());$('#checkoutButton').disabled=!state.cart.length}
function openCart(){const x=$('#cartDrawer');x.classList.add('is-open');x.setAttribute('aria-hidden','false')}
function closeCart(){const x=$('#cartDrawer');x.classList.remove('is-open');x.setAttribute('aria-hidden','true')}
function openProduct(id){const p=state.products.find(x=>x.id===id);if(!p)return;state.selected=p;state.size='';state.colour='';const imgs=(p.images?.length?p.images:[p.image]).filter(Boolean),price=priceOf(p),sold=soldOut(p);$('#productViewTitle').textContent=p.name||'Rushgal piece';$('#productViewCategory').textContent=p.category||'Rushgal';$('#productViewPrice').textContent=price?money(price):'Price on request';$('#productViewDescription').textContent=p.description||'';$('#productViewMain').src=imgs[0]||'';$('#productViewGallery').innerHTML=imgs.map((src,i)=>`<button type="button" data-image="${i}" class="${i?'':'is-active'}"><img src="${esc(src)}" alt=""></button>`).join('');$('#sizeOptions').innerHTML=(Array.isArray(p.sizes)&&p.sizes.length?p.sizes:[]).map(s=>`<button type="button" data-size="${esc(s)}">${esc(s)}</button>`).join('')||'<span class="muted">One size</span>';$('#colourOptions').innerHTML=(Array.isArray(p.colours)&&p.colours.length?p.colours:[]).map(c=>`<button type="button" data-colour="${esc(c)}">${esc(c)}</button>`).join('')||'<span class="muted">Standard colour</span>';$('#productViewQuantity').value=1;const b=$('#productViewAdd');b.disabled=!price||sold;b.textContent=!price?'Price on request':sold?'Sold out':'Add to bag';$('#productView').classList.add('is-open');$('#productView').setAttribute('aria-hidden','false')}
function closeProduct(){const x=$('#productView');x.classList.remove('is-open');x.setAttribute('aria-hidden','true')}
function addSelected(){const p=state.selected,price=priceOf(p);if(!p||!price||soldOut(p))return;let q=Math.max(1,parseInt($('#productViewQuantity').value,10)||1),stock=stockOf(p);if(stock!==null)q=Math.min(q,stock);const old=state.cart.find(i=>i.id===p.id&&i.size===state.size&&i.colour===state.colour);if(old)old.qty=Math.min(old.qty+q,stock??Infinity);else state.cart.push({id:p.id,name:p.name,price,image:imageOf(p),qty:q,size:state.size,colour:state.colour});saveCart();renderCart();closeProduct();openCart()}
function renderProducts(){const grid=$('#shopGrid');if(!grid)return;const f=$('#shopFilter')?.value||'all';const list=f==='all'?state.products:state.products.filter(p=>(p.category||'').toLowerCase().includes(f));grid.innerHTML=list.length?list.map(p=>{const price=priceOf(p),sold=soldOut(p);return `<article class="shop-card"><div class="shop-card-image"><img src="${esc(imageOf(p))}" alt="${esc(p.name||'Rushgal product')}" loading="lazy">${sold&&price?'<span class="shop-card-badge">Sold out</span>':''}</div><div class="shop-card-body"><div class="shop-card-top"><div><span class="shop-card-category">${esc(p.category||'Rushgal')}</span><h3>${esc(p.name||'Untitled piece')}</h3></div><span class="shop-price">${price?money(price):'Price on request'}</span></div><div class="shop-card-actions"><button type="button" data-view="${esc(p.id)}">View</button><button type="button" class="add" data-add="${esc(p.id)}" ${price&&!sold?'':'disabled'}>${!price?'Price on request':sold?'Sold out':'Add to bag'}</button></div></div></article>`}).join(''):'<div class="shop-empty"><strong>No pieces available yet.</strong> Rushgal can add products from the admin dashboard.</div>'}
async function loadProducts(){try{const snap=await getDocs(collection(db,'products'));state.products=snap.docs.map(d=>({id:d.id,...d.data()})).filter(p=>p.status!=='draft'&&p.active!==false)}catch(e){console.error(e);state.products=[]}renderProducts()}
async function loadZones(){try{const snap=await getDocs(collection(db,'deliveryZones'));state.zones=snap.docs.map(d=>({id:d.id,...d.data()})).filter(z=>z.active!==false);const s=$('#deliveryZone');s.innerHTML='<option value="">Select your delivery area</option>'+state.zones.map(z=>`<option value="${esc(z.id)}">${esc(z.name)} — ${money(z.fee)}</option>`).join('')}catch(e){console.error(e)}}
function updateSummary(){const sub=subtotal(),total=sub+state.fee;$('#checkoutSubtotal').textContent=money(sub);$('#deliveryFee').textContent=state.fee?money(state.fee):'FREE';$('#checkoutTotal').textContent=money(total);$('#deliveryFields')?.classList.toggle('is-hidden',state.fulfilment!=='delivery');const b=$('.checkout-form .place');if(b)b.disabled=!state.cart.length||(state.fulfilment==='delivery'&&!$('#deliveryZone')?.value)}
function zoneChanged(){const z=state.zones.find(x=>x.id===$('#deliveryZone')?.value);state.fee=state.fulfilment==='delivery'?Number(z?.fee||0):0;updateSummary()}
async function validateStock(){const errors=[];for(const i of state.cart){const p=state.products.find(x=>x.id===i.id);if(!p){errors.push(`${i.name} is no longer available.`);continue}const price=priceOf(p),stock=stockOf(p);if(!price){errors.push(`${i.name} has no valid price.`);continue}if(soldOut(p)||stock===0)errors.push(`${i.name} is currently unavailable.`);else if(stock!==null&&i.qty>stock)errors.push(`${i.name}: only ${stock} available.`)}return errors}
async function placeOrder(e){e.preventDefault();const f=e.currentTarget,d=new FormData(f),status=$('#checkoutStatus'),button=f.querySelector('.place');if(state.fulfilment==='delivery'&&!$('#deliveryZone')?.value){status.textContent='Please select your delivery area.';status.classList.add('show');return}const errors=await validateStock();if(errors.length){status.textContent=errors.join(' ');status.classList.add('show');return}const z=state.zones.find(x=>x.id===$('#deliveryZone')?.value),sub=subtotal(),delivery=state.fulfilment==='delivery'?state.fee:0;const order={trackingCode:'RG-'+Math.random().toString(36).slice(2,8).toUpperCase(),customer:{name:String(d.get('name')||'').trim(),phone:String(d.get('phone')||'').trim(),email:String(d.get('email')||'').trim()},fulfilment:state.fulfilment,deliveryZone:state.fulfilment==='delivery'?{id:z?.id||null,name:z?.name||'',fee:Number(z?.fee||0)}:null,address:state.fulfilment==='delivery'?{address:String(d.get('address')||'').trim(),area:z?.name||'',notes:String(d.get('notes')||'').trim(),latitude:d.get('latitude')||null,longitude:d.get('longitude')||null}:null,items:state.cart.map(i=>({productId:i.id,name:i.name,price:Number(i.price)||0,quantity:Number(i.qty)||0,size:i.size||'',colour:i.colour||''})),subtotal:sub,deliveryFee:delivery,total:sub+delivery,paymentMethod:'pay_on_delivery',status:'new',createdAt:serverTimestamp()};button.disabled=true;status.textContent='Submitting your order…';status.classList.add('show');try{await addDoc(collection(db,'orders'),order);localStorage.setItem('rushgal-last-order',JSON.stringify({trackingCode:order.trackingCode,phone:order.customer.phone}));state.cart=[];saveCart();renderCart();f.reset();state.fulfilment='delivery';state.fee=0;$('#deliveryZone').value='';updateSummary();closeCheckout();$('#confirmationCode').textContent=order.trackingCode;$('#confirmationTotal').textContent=money(order.total);$('#confirmationFulfilment').textContent=order.fulfilment==='delivery'?'Home delivery':'Store pickup';$('#orderConfirmation').classList.add('is-open');$('#orderConfirmation').setAttribute('aria-hidden','false');status.classList.remove('show')}catch(err){console.error(err);status.textContent='We could not submit the order. Please try again or contact Rushgal on WhatsApp.';status.classList.add('show')}finally{button.disabled=false}}
function closeCheckout(){$('#checkoutModal').classList.remove('is-open')}
function closeConfirmation(){$('#orderConfirmation').classList.remove('is-open')}
function bind(){state.cart=loadCart();updateCount();renderCart();$('#shopFilter')?.addEventListener('change',renderProducts);$('#cartOpen')?.addEventListener('click',openCart);$('#cartOpen2')?.addEventListener('click',openCart);$('#cartClose')?.addEventListener('click',closeCart);$('#cartBackdrop')?.addEventListener('click',closeCart);$('#checkoutButton')?.addEventListener('click',()=>{if(state.cart.length){closeCart();$('#checkoutModal').classList.add('is-open');updateSummary()}});$('#checkoutClose')?.addEventListener('click',closeCheckout);$('#checkoutCancel')?.addEventListener('click',closeCheckout);$('#closeProductView')?.addEventListener('click',closeProduct);$('#productViewAdd')?.addEventListener('click',addSelected);$('#deliveryZone')?.addEventListener('change',zoneChanged);$('#useLocation')?.addEventListener('click',()=>{const s=$('#locationStatus');if(!navigator.geolocation){s.textContent='Location is not supported on this browser.';return}s.textContent='Requesting your location…';navigator.geolocation.getCurrentPosition(p=>{$('#latitude').value=p.coords.latitude.toFixed(6);$('#longitude').value=p.coords.longitude.toFixed(6);s.textContent='✓ Location captured.'},()=>s.textContent='Location unavailable. Enter your address manually.',{enableHighAccuracy:true,timeout:10000})});$$('input[name="fulfilment"]').forEach(r=>r.addEventListener('change',()=>{state.fulfilment=r.value;state.fee=0;zoneChanged()}));$('#checkoutForm')?.addEventListener('submit',placeOrder);$('#confirmationClose')?.addEventListener('click',closeConfirmation);$('#confirmationClose2')?.addEventListener('click',closeConfirmation);$('#shopGrid')?.addEventListener('click',e=>{const v=e.target.closest('[data-view]'),a=e.target.closest('[data-add]');if(v)openProduct(v.dataset.view);else if(a)openProduct(a.dataset.add)});$('#productView')?.addEventListener('click',e=>{const im=e.target.closest('[data-image]'),si=e.target.closest('[data-size]'),co=e.target.closest('[data-colour]');if(im){const imgs=(state.selected?.images?.length?state.selected.images:[state.selected?.image]).filter(Boolean);$('#productViewMain').src=imgs[Number(im.dataset.image)]||'';$$('[data-image]').forEach(x=>x.classList.toggle('is-active',x===im))}if(si){state.size=si.dataset.size;$$('[data-size]').forEach(x=>x.classList.toggle('is-active',x===si))}if(co){state.colour=co.dataset.colour;$$('[data-colour]').forEach(x=>x.classList.toggle('is-active',x===co))}});$('#cartItems')?.addEventListener('click',e=>{const m=e.target.closest('[data-minus]'),p=e.target.closest('[data-plus]');if(!m&&!p)return;const id=(m||p).dataset[m?'minus':'plus'],item=state.cart.find(i=>i.id===id);if(!item)return;const product=state.products.find(x=>x.id===id),stock=stockOf(product);item.qty+=m?-1:1;if(stock!==null)item.qty=Math.min(item.qty,stock);if(item.qty<=0)state.cart=state.cart.filter(x=>x!==item);saveCart();renderCart()})}
document.addEventListener('DOMContentLoaded',()=>{bind();loadProducts();loadZones()});